//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP.DataAcces
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Archivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Archivo()
        {
            this.Reporte = new ObservableCollection<Reporte>();
        }
    
        public Nullable<System.DateTime> Fechaentrega { get; set; }
        public byte[] Archivo1 { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Validado { get; set; }
        public int ArchivoID { get; set; }
        public Nullable<int> ExpedienteID { get; set; }
        public string Tipodocumento { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reporte> Reporte { get; set; }
    }
}
