//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP.DataAcces
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Archivo
    {
        public Nullable<System.DateTime> Fechaentrega { get; set; }
        public string Rutaubicación { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Validado { get; set; }
        public int ArchivoID { get; set; }
        public Nullable<int> ExpedienteID { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Reporte Reporte { get; set; }
    }
}
