//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP.DataAcces
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Organización
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organización()
        {
            this.Proyecto = new ObservableCollection<Proyecto>();
            this.Responsableproyecto = new ObservableCollection<Responsableproyecto>();
        }
    
        public string Calle { get; set; }
        public string Codigopostal { get; set; }
        public string Colonia { get; set; }
        public string Correo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Numext { get; set; }
        public string Telefono { get; set; }
        public int Activo { get; set; }
        public int OrganizaciónID { get; set; }
        public string Sector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Proyecto> Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Responsableproyecto> Responsableproyecto { get; set; }
    }
}
