//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP.DataAcces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCPPContext : DbContext
    {
        public SCPPContext()
            : base("name=SCPPContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<Coordinador> Coordinador { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Inscripción> Inscripción { get; set; }
        public virtual DbSet<Organización> Organización { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<Responsableproyecto> Responsableproyecto { get; set; }
        public virtual DbSet<Selecciónproyecto> Selecciónproyecto { get; set; }
    }
}
