//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Coordinador
    {
        public string Apellidomaterno { get; set; }
        public string Apellidopaterno { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public string Correopersonal { get; set; }
        public string Contraseña { get; set; }
    }
}
