//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Inscripción
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscripción()
        {
            this.Expediente = new ObservableCollection<Expediente>();
        }
    
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Periodo { get; set; }
        public string Tipo { get; set; }
        public int InscripciónID { get; set; }
        public string Matriculaestudiante { get; set; }
        public Nullable<int> Claveproyecto { get; set; }
        public Nullable<int> GrupoID { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Expediente> Expediente { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
