//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Reporte
    {
        public Nullable<int> Horasreportadas { get; set; }
        public string Tiporeporte { get; set; }
        public int ReporteID { get; set; }
    
        public virtual Archivo Archivo { get; set; }
    }
}
