//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPP
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Selecciónproyecto
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string PeriodoID { get; set; }
        public int SelecciónproyectoID { get; set; }
        public string Matriculaestudiante { get; set; }
        public Nullable<int> Claveproyecto { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
